Adding changes from fetching AAD details from rahul's pr
rapatchi/azure-cli-extensions pull request #2
Opened 2020-09-02 10:26 UTC by alphaWizard

---

Since I couldnt rebase easily with our recent changes because of various conflicts since akash had made some restructuring in the code. I have picked your changes manually. You can have a look at it once.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2020-09-04 10:52 UTC, rapatchi requested changes

2020-09-04 10:52 UTC, rapatchi commented on src/connectedk8s/azext_connectedk8s/custom.py
> +                raise
Let's raise a User Fault here.

2020-09-04 10:52 UTC, rapatchi commented on src/connectedk8s/azext_connectedk8s/custom.py
> +    if context_name is not None:
Please make you have tested this path as well passing custom context name.

2020-09-04 10:52 UTC, rapatchi commented on src/connectedk8s/azext_connectedk8s/custom.py
> +            logger.warning('%s has permissions "%s".\nIt should be readable and writable only by its owner.',
Should we raise a cli error as well ?

2020-09-04 11:38 UTC, alphaWizard commented on src/connectedk8s/HISTORY.rst
> +* `az connectedk8s get-credentials`: Added support for list cluster user ceredentials
Will mention.

2020-09-04 11:38 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +                raise
okay

2020-09-04 11:38 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +    if context_name is not None:
okay, will test that.

2020-09-04 11:39 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +            logger.warning('%s has permissions "%s".\nIt should be readable and writable only by its owner.',
Yeah, i think we should. Will do accordingly.

2020-09-04 13:59 UTC, alphaWizard commented on src/connectedk8s/HISTORY.rst
> +* `az connectedk8s get-credentials`: Added support for list cluster user ceredentials
Done

2020-09-04 14:08 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +    if context_name is not None:
Yeah, passing custom context name also work.

2020-09-07 05:51 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        raise CLIError("Failed to get credentials")
Add exception telemetry and set user fault accordingly. Also, cant we print the exception message in the error itself? Do we need that to be a warning message

2020-09-07 05:54 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        credentialResults = client.list_cluster_user_credentials(resource_group_name, cluster_name)
better to have separate try catch blocks for lines 736 and 737. This will ease debugging issues in telemetry

2020-09-07 06:19 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        telemetry.add_extension_event('connectedk8s', {'Context.Default.AzureCLI.IsAADEnabled': is_aad_enabled})
Lets keep this event outside if statement

2020-09-07 06:26 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        kube_config = os.getenv('KUBECONFIG') if os.getenv('KUBECONFIG') else os.path.join(os.path.expanduser('~'), '.kube', 'config')
How are we handling the scenarios where the KUBECONFIG env var is has more than one kubeconfig?

2020-09-07 06:31 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        kube_config = os.getenv('KUBECONFIG') if os.getenv('KUBECONFIG') else os.path.join(os.path.expanduser('~'), '.kube', 'config')
It corresponds to the current context; all_contexts, current_context = config.list_kube_config_contexts()

2020-09-07 06:31 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        telemetry.add_extension_event('connectedk8s', {'Context.Default.AzureCLI.IsAADEnabled': is_aad_enabled})
okay

2020-09-07 06:33 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        credentialResults = client.list_cluster_user_credentials(resource_group_name, cluster_name)
okay

2020-09-07 06:45 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        raise CLIError("Failed to get credentials")
Okay, will append the exception as a string to CLIerror itself.

2020-09-07 06:51 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        retrieved_aad_server_app_id, retrieved_aad_client_app_id, retrieved_aad_tenant_id = get_user_aad_details(kube_config, user)
Lets keep a separate try catch for this line. Also, the exception telemetry in  get_user_aad_details can use a different faultType than User_Not_Found_Type.

2020-09-07 06:53 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        config_data = yaml.safe_load(f)
Add a separate exception if we are not able to load the kubeconfig

2020-09-07 06:59 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +                raise CLIError("Could not create a kubeconfig directory")
Add exception telemetry at all places where we raise errors

2020-09-07 07:01 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        addition['contexts'][0]['name'] = context_name
Add try catch here

2020-09-07 07:03 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +    with open(existing_file, 'w+') as stream:
try catch

2020-09-07 07:03 UTC, akashkeshari requested changes
Left comments

2020-09-07 07:09 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        kube_config = os.getenv('KUBECONFIG') if os.getenv('KUBECONFIG') else os.path.join(os.path.expanduser('~'), '.kube', 'config')
Okay, but how will you handle reading user_aad_details if there are multiple kubeconfigs?

2020-09-07 07:25 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        retrieved_aad_server_app_id, retrieved_aad_client_app_id, retrieved_aad_tenant_id = get_user_aad_details(kube_config, user)
okay

2020-09-07 07:29 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        config_data = yaml.safe_load(f)
okay

2020-09-07 07:39 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        addition['contexts'][0]['name'] = context_name
okay

2020-09-07 08:11 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +    with open(existing_file, 'w+') as stream:
okay

2020-09-07 09:47 UTC, alphaWizard commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        kube_config = os.getenv('KUBECONFIG') if os.getenv('KUBECONFIG') else os.path.join(os.path.expanduser('~'), '.kube', 'config')
From the kubecontext(if provided) or current context, it fetches the user part, and then passes (kubeconfig, user) to get_user_aad_details(), where it retrieves that user aad details.

2020-09-07 12:56 UTC, alphaWizard commented
I have made all asked changes and have moved the pr to main repo https://github.com/Azure/azure-cli-extensions/pull/2314

2020-09-07 14:07 UTC, akashkeshari commented on src/connectedk8s/azext_connectedk8s/custom.py
> +        kube_config = os.getenv('KUBECONFIG') if os.getenv('KUBECONFIG') else os.path.join(os.path.expanduser('~'), '.kube', 'config')
My only concern is line # 513 below. If the KUBECONFIG env var is set to point to multiple configs, what will happen?

2020-09-09 07:05 UTC, merged